#!/usr/bin/env sh
set -e

. "$(dirname -- "$0")/../venv/bin/activate"
ruff check .                                    # lint
ruff format --check .                           # format check
pyright                                         # type check
npx --no-install prettier --check "**/*.md"     # markdown format check
